image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - elmTooling.elm-ls-vscode@0.8.0:rb3k4mPelyC4Fqod9UBvvA==
tasks:
  - init: elm make src/Main.elm
    command: python3 -m http.server
ports:
  - port: 8000
    onOpen: open-preview
